# Generated by Django 5.1.6 on 2025-02-18 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('institucion', models.CharField(max_length=50)),
                ('materia', models.CharField(max_length=50)),
            ],
        ),
    ]
