# Generated by Django 5.1.6 on 2025-03-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
    ]
