# Generated by Django 5.1.6 on 2025-03-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_alumno_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='avatar_alumno',
            field=models.ImageField(blank=True, null=True, upload_to='avatares_alumnos'),
        ),
    ]
